// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.1";

// src/lib/mcp/tools/search-quran.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z } from "npm:zod@^3.25.76";
var search_quran_default = defineTool({
  name: "search_quran",
  title: "\u0628\u062D\u062B \u0641\u064A \u0627\u0644\u0642\u0631\u0622\u0646 \u0627\u0644\u0643\u0631\u064A\u0645",
  description: "Search the Holy Quran for verses matching an Arabic keyword or phrase. Returns matching ayahs with their surah name, ayah number, and Arabic text.",
  inputSchema: {
    query: z.string().min(1).describe("Arabic keyword or phrase to search for (e.g. \u0627\u0644\u0631\u062D\u0645\u0646\u060C \u0627\u0644\u0635\u0628\u0631\u060C \u0627\u0644\u062C\u0646\u0629)."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of matches to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const cap = limit ?? 20;
    const url = `https://api.alquran.cloud/v1/search/${encodeURIComponent(query)}/all/quran-uthmani`;
    const res = await fetch(url);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `\u062A\u0639\u0630\u0651\u0631 \u0627\u0644\u0627\u062A\u0635\u0627\u0644 \u0628\u0645\u0635\u062F\u0631 \u0627\u0644\u0642\u0631\u0622\u0646 (HTTP ${res.status}).` }],
        isError: true
      };
    }
    const json = await res.json();
    const matches = (json?.data?.matches ?? []).slice(0, cap).map((m) => ({
      surah: m.surah?.name,
      surahEnglish: m.surah?.englishName,
      surahNumber: m.surah?.number,
      ayah: m.numberInSurah,
      text: m.text
    }));
    return {
      content: [
        {
          type: "text",
          text: matches.length === 0 ? `\u0644\u0627 \u062A\u0648\u062C\u062F \u0646\u062A\u0627\u0626\u062C \u0644\u0644\u0628\u062D\u062B \u0639\u0646: ${query}` : matches.map(
            (m) => `${m.surah} (${m.surahNumber}:${m.ayah}) \u2014 ${m.text}`
          ).join("\n\n")
        }
      ],
      structuredContent: { query, count: matches.length, matches }
    };
  }
});

// src/lib/mcp/tools/get-ayah.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_ayah_default = defineTool2({
  name: "get_ayah",
  title: "\u062C\u0644\u0628 \u0622\u064A\u0629 \u0645\u0639 \u0627\u0644\u062A\u0641\u0633\u064A\u0631",
  description: "Fetch a specific ayah from the Quran with its Arabic text, English translation, and Arabic tafsir (Al-Muyassar).",
  inputSchema: {
    surah: z2.number().int().min(1).max(114).describe("Surah number (1\u2013114)."),
    ayah: z2.number().int().min(1).max(286).describe("Ayah number within the surah.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ surah, ayah }) => {
    const ref = `${surah}:${ayah}`;
    const [arabicRes, translationRes, tafsirRes] = await Promise.all([
      fetch(`https://api.alquran.cloud/v1/ayah/${ref}/quran-uthmani`),
      fetch(`https://api.alquran.cloud/v1/ayah/${ref}/en.sahih`),
      fetch(`https://api.alquran.cloud/v1/ayah/${ref}/ar.muyassar`)
    ]);
    if (!arabicRes.ok) {
      return {
        content: [{ type: "text", text: `\u062A\u0639\u0630\u0651\u0631 \u062C\u0644\u0628 \u0627\u0644\u0622\u064A\u0629 (${ref}).` }],
        isError: true
      };
    }
    const arabic = await arabicRes.json();
    const translation = translationRes.ok ? await translationRes.json() : null;
    const tafsir = tafsirRes.ok ? await tafsirRes.json() : null;
    const data = {
      reference: ref,
      surah: arabic?.data?.surah?.name,
      surahEnglish: arabic?.data?.surah?.englishName,
      juz: arabic?.data?.juz,
      arabic: arabic?.data?.text,
      translation: translation?.data?.text ?? null,
      tafsir: tafsir?.data?.text ?? null
    };
    return {
      content: [
        {
          type: "text",
          text: `${data.surah} (${ref})

${data.arabic}

Translation: ${data.translation ?? "\u2014"}

\u0627\u0644\u062A\u0641\u0633\u064A\u0631 \u0627\u0644\u0645\u064A\u0633\u0631: ${data.tafsir ?? "\u2014"}`
        }
      ],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-surah-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_surah_info_default = defineTool3({
  name: "get_surah_info",
  title: "\u0645\u0639\u0644\u0648\u0645\u0627\u062A \u0627\u0644\u0633\u0648\u0631\u0629",
  description: "Get metadata for a Quran surah: Arabic name, English name, revelation type (Meccan/Medinan), ayah count, and starting juz.",
  inputSchema: {
    surah: z3.number().int().min(1).max(114).describe("Surah number (1\u2013114).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ surah }) => {
    const res = await fetch(`https://api.alquran.cloud/v1/surah/${surah}`);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `\u062A\u0639\u0630\u0651\u0631 \u062C\u0644\u0628 \u0645\u0639\u0644\u0648\u0645\u0627\u062A \u0627\u0644\u0633\u0648\u0631\u0629 (${surah}).` }],
        isError: true
      };
    }
    const json = await res.json();
    const d = json?.data ?? {};
    const info = {
      number: d.number,
      name: d.name,
      englishName: d.englishName,
      englishNameTranslation: d.englishNameTranslation,
      revelationType: d.revelationType,
      numberOfAyahs: d.numberOfAyahs
    };
    return {
      content: [
        {
          type: "text",
          text: `${info.name} (${info.englishName} \u2014 ${info.englishNameTranslation})
\u0631\u0642\u0645 \u0627\u0644\u0633\u0648\u0631\u0629: ${info.number}
\u0639\u062F\u062F \u0627\u0644\u0622\u064A\u0627\u062A: ${info.numberOfAyahs}
\u0646\u0648\u0639 \u0627\u0644\u0646\u0632\u0648\u0644: ${info.revelationType === "Meccan" ? "\u0645\u0643\u064A\u0629" : "\u0645\u062F\u0646\u064A\u0629"}`
        }
      ],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-prayer-times.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_prayer_times_default = defineTool4({
  name: "get_prayer_times",
  title: "\u0645\u0648\u0627\u0642\u064A\u062A \u0627\u0644\u0635\u0644\u0627\u0629",
  description: "Get today's Islamic prayer times (Fajr, Dhuhr, Asr, Maghrib, Isha) for a given city and country using the Aladhan API.",
  inputSchema: {
    city: z4.string().min(1).describe("City name in English or Arabic (e.g. Riyadh, Cairo, Istanbul)."),
    country: z4.string().min(1).describe("Country name in English (e.g. Saudi Arabia, Egypt, Turkey)."),
    method: z4.number().int().min(0).max(15).optional().describe("Calculation method id (Aladhan). Default 4 (Umm Al-Qura).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ city, country, method }) => {
    const url = `https://api.aladhan.com/v1/timingsByCity?city=${encodeURIComponent(city)}&country=${encodeURIComponent(country)}&method=${method ?? 4}`;
    const res = await fetch(url);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `\u062A\u0639\u0630\u0651\u0631 \u062C\u0644\u0628 \u0645\u0648\u0627\u0642\u064A\u062A \u0627\u0644\u0635\u0644\u0627\u0629 \u0644\u0640 ${city}, ${country}.` }],
        isError: true
      };
    }
    const json = await res.json();
    const t = json?.data?.timings ?? {};
    const date = json?.data?.date?.readable ?? "";
    const hijri = json?.data?.date?.hijri?.date ?? "";
    const rows = ["Fajr", "Sunrise", "Dhuhr", "Asr", "Maghrib", "Isha"].filter((k) => t[k]).map((k) => `${k}: ${t[k]}`).join("\n");
    return {
      content: [
        {
          type: "text",
          text: `\u0645\u0648\u0627\u0642\u064A\u062A \u0627\u0644\u0635\u0644\u0627\u0629 \u2014 ${city}, ${country}
${date} (${hijri})

${rows}`
        }
      ],
      structuredContent: {
        city,
        country,
        date,
        hijri,
        timings: t
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "quran-heart-mcp",
  title: "\u0642\u0644\u0628 \u0627\u0644\u0642\u0631\u0622\u0646 \u2014 Quran Heart",
  version: "0.1.0",
  instructions: "\u0623\u062F\u0648\u0627\u062A \u0625\u0633\u0644\u0627\u0645\u064A\u0629 \u0639\u0627\u0645\u0629 \u0645\u0646 \u062A\u0637\u0628\u064A\u0642 \u0642\u0644\u0628 \u0627\u0644\u0642\u0631\u0622\u0646: \u0627\u0644\u0628\u062D\u062B \u0641\u064A \u0627\u0644\u0642\u0631\u0622\u0646 \u0627\u0644\u0643\u0631\u064A\u0645\u060C \u062C\u0644\u0628 \u0622\u064A\u0629 \u0645\u0639 \u062A\u0641\u0633\u064A\u0631\u0647\u0627\u060C \u0645\u0639\u0644\u0648\u0645\u0627\u062A \u0627\u0644\u0633\u0648\u0631\u060C \u0648\u0645\u0648\u0627\u0642\u064A\u062A \u0627\u0644\u0635\u0644\u0627\u0629 \u0644\u0623\u064A \u0645\u062F\u064A\u0646\u0629.",
  tools: [search_quran_default, get_ayah_default, get_surah_info_default, get_prayer_times_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
